version: '3.9'

services:
  web:
    build: .
    command: gunicorn social_network.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=social_network.settings
